title:              "요즘의 #키워드"
tagline:            "또래의 시선으로 MZ세대 분석하기"
email:              "sb10044@naver.com"
description:        "또래가 본 MZ세대의 취향과 생각을 분석하는 공간"
author:             "숲숲"
baseurl:            "/"
url:                "https://subsub.kr"
locale:             "ko_KR"
thumbnail:          "/img/blog_thumbnail_v2.jpg"

# Social Profiles
instagram_username: sub_sub22
facebook_username:  sb10044
twitter_username:   sb10044
linkedin_username:  sb10044

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate

# 블로그 disqus shortname
disqus:
  shortname: https-subsub-kr
